### ISSUE TITLE
[Coderschool] Week 2 lab assignment is finished.

### ISSUE THREAD

**Issue by tiennth** [tiennth/coderschool-yelp#1]
I have finished my assignment for week 2
Please take a look.

/cc @coderschoolreview

**Comment by minhchau273** [comment]
:+1: Fantastic job with the submission - one of the best of the week. :horse_racing:  The primary challenge of this homework was to learn how to use UITableView to manage a complex form, establish communication between view controllers, and apply the correct Auto Layout constraints. 

This was a challenging assignment, congrats on completing it successfully!

## Grading Summary:
- **Functionality**: Excellent
- **Code Style**: Good
- **Visual Design**: Good
- **Usability**: Excellent

#### **Overall**: Excellent

## Detailed Notes
- Nice work specifying the Auto Layout constraints.
- Nice work linking the filter model with the controls. See this [popular form library](https://github.com/nicklockwood/FXForms) for an alternative to implementing forms manually.
- Good job using `unwind` to pass data between view controllers. But consider defining a custom protocol to capture the filter change event.
- Great job implementing map view for restaurant results. It'd be better if when change to map view, the map focuses on one of the results. For now, in some cases, after I search and change to map view, I don't see any pin location though it has the results.

**Comment by tiennth** [comment]
Thank you very much @minhchau273
